### PR TITLE
Add `from` helper methods

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by DDoS** [comment]
Other than using the ZERO constant where possible, I don't see the point of this.

**Comment by kashike** [comment]
That *is* the point.

**Comment by kashike** [comment]
In addition to that, adding a `of(n)` method to simply using the same value for each value.

**Comment by DDoS** [comment]
Needs tests, make sure the components aren't accidentally switched around when passed from `of` to the constructor.

**Comment by Zidane** [comment]
@DDoS stole my words. Needs tests indeed.

**Pull request merged**
